### ISSUE TITLE
Crear fichero de usuarios de la aplicación (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-burgoboy#1]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo añadirle más funcionalidad.

El menú está bien para empezar porque tiene dos niveles, pero debería estar un bucle para que se vuelva a repetir salvo que el usuario indique que quiere salir.

Debéis describir en el archivo principal los "Objetivos del trabajo" con la descripción más detallada de cada una de las funcionalidades. No quedan del todo claras y no sé cuál será el alcance.

El hito que os propongo para el 20 de abril es que creéis un fichero de texto (.txt) con todos los usuarios de la aplicación y contempléis una clasificación con los puntos que han obtenido en las partidas. Os aconsejo que almacenéis los datos en un vector de estructuras y que se muestren los usuarios en alguna de las opciones. Quizá estaría bien que los usuarios puedan acceder con usuario y contraseña.

Si no teníais pensado hacer esto, proponedme otra cosa pero el uso de vectores de estructuras es obligatorio.

Además de esto, os animo a que sigáis programando más funcionalidades.

Una cosa que he visto es que llamáis a las funciones antes de declarar las variables. Por favor, se declaran antes las variables, todas juntas.

Un saludo y buenas vacaciones.

**Comment by raquelcedazo** [comment]
Cerrar la issue si ya está completado lo que os pedía, por favor.

**Comment by SamuelHornsbyAltares** [comment]
Todavía hay que arreglar una cosa del fichero, pero ya está añadido.
